name: inmas-ml
dependencies:
  - python>=3.7
  - jupyter
  - numpy
  - pandas
  - ipykernel
  - matplotlib>=3.6.2
  - statsmodels
  - seaborn>=0.12
  - scikit-learn>=1.3
  - pytorch>=1.13.1
  - torchvision